spring.datasource.url=jdbc:mysql://localhost:3306/saloon_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
saloon.app.jwtSecret=saloonSecretKeySaloonSecretKeySaloonSecretKeySaloonSecretKey
saloon.app.jwtExpirationMs=86400000
